on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  pull-request: write
  contents: write

jobs:
  goreadme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: posener/goreadme@v1
        with:
          badge-godoc: true
          badge-goreadme: true
          badge-goreportcard: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          import-path: "github.com/avocatl/conversor"
          recursive: true
