name: Golang testing
on:
  push:
    paths-ignore:
      - "docs/**"
      - "**.md"
      - ".github/**.md"
      - ".github/**/**.md"
  pull_request:
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16.x, 1.17.x]
    name: Go ${{ matrix.go }} check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./pkg/...
